#cloud-config
disk_setup:
  ephemeral0:
    table_type: 'gpt'
    layout:
      - 100
    overwrite: true

fs_setup:
  - label: ephemeral0.1
    filesystem: 'ext4'
    device: 'ephemeral0.1'

mounts:
  - [ ephemeral0.1 /var/lib/condor ]

runcmd:
  # Set up condor with control node's IP and the pool password
  - sudo curl -fsSL https://get.htcondor.com | GET_HTCONDOR_PASSWORD=${condor_pool_pass} /bin/bash -s -- --no-dry-run --central-manager $(hostname -i | awk '{print $1}')
  - sudo mv /home/ubuntu/condor_config.local /etc/condor/condor_config.local
  # And set the log dir with proper permissions
  - sudo chown -R condor /var/log/condor
  - sudo chgrp -R condor /var/log/condor
  - sudo chmod -R g+rwx /var/log/condor
  # Enable Condor to start on system boot
  - sudo systemctl enable condor
  - sudo systemctl start condor
  # Disable SSH so regular users can't log in manually
  - sudo groupadd ssh-condor
  - sudo usermod -a -G ssh-condor ubuntu
  - echo 'AllowGroups ssh-condor' | sudo tee -a /etc/ssh/sshd_config
  # Enable and start fail2ban
  - sudo systemctl enable fail2ban
  - sudo systemctl start fail2ban