#cloud-config
disk_setup:
  ephemeral0:
    table_type: gpt
    layout: true
    overwrite: true

fs_setup:
  - device: ephemeral0.1
    filesystem: ext4

mounts:
  - ["ephemeral0.1", "/var/lib/prometheus"]

runcmd:
  # Fill in the OpenStack information into the prometheus config
  - sudo sed -i 's/os_idendpoint/${id_endpoint}/g' /etc/prometheus/prometheus.yml
  - sudo sed -i 's/os_username/${username}/g' /etc/prometheus/prometheus.yml
  - sudo sed -i 's/os_password/${password}/g' /etc/prometheus/prometheus.yml
  - sudo sed -i 's/os_project_name/${project_name}/g' /etc/prometheus/prometheus.yml
  - sudo sed -i 's/os_project_id/${project_id}/g' /etc/prometheus/prometheus.yml
  - sudo sed -i 's/os_region/${region}/g' /etc/prometheus/prometheus.yml
  - sudo sed -i 's/os_domain_name/${domain_name}/g' /etc/prometheus/prometheus.yml
  # The monitoring directories are a few nested directories deep, but it those aren't directly mountable
  # Mount the root first, then mount the subdirs that actually map to the monitor locations
  - sudo mkdir /etc/grafana /etc/prometheus /var/lib/prometheus /var/lib/grafana
  - echo "${nfs_home}                                 /illume               nfs _netdev,auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0" | sudo tee -a /etc/fstab
  - echo "/illume/illume/grafana/grafana_etc          /etc/grafana          none _netdev,bind" | sudo tee -a /etc/fstab
  - echo "/illume/illume/grafana/grafana_var          /var/lib/grafana      none _netdev,bind" | sudo tee -a /etc/fstab
  - echo "/illume/illume/prometheus/prometheus_etc    /etc/prometheus       none _netdev,bind" | sudo tee -a /etc/fstab
  - echo "/illume/illume/prometheus/prometheus_var    /var/lib/prometheus   none _netdev,bind" | sudo tee -a /etc/fstab
  - sudo mount -a
  # Enable and start Prometheus
  - sudo systemctl daemon-reload
  - sudo systemctl start prometheus
  - sudo systemctl enable prometheus
  # Enable and start Grafana
  - sudo systemctl enable grafana-server
  - sudo systemctl start grafana-server
  # Disable SSH so regular users can't log in manually
  - sudo groupadd ssh-condor
  - sudo usermod -a -G ssh-condor ubuntu
  - echo 'AllowGroups ssh-condor' | sudo tee -a /etc/ssh/sshd_config
  # Enable and start fail2ban
  - sudo systemctl enable fail2ban
  - sudo systemctl start fail2ban
