#cloud-config
runcmd:
  - sudo sed -i 's/127.0.0.1/${openLDAP_IP}/' /etc/phpldapadmin/config.php,
  - sudo sed -i 's/dc=example,dc=com/dc=illume,dc=systems/' /etc/phpldapadmin/config.php,
  - sudo systemctl restart apache2